--- 상품 별 오프라인 매출 구하기
SELECT PROD.PRODUCT_CODE, SUM(PROD.PRICE * SALE.SALES_AMOUNT) AS SALES
FROM PRODUCT PROD
JOIN (SELECT PRODUCT_ID, SALES_AMOUNT FROM OFFLINE_SALE) AS SALE
ON PROD.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY PROD.PRODUCT_ID
ORDER BY SALES DESC, PROD.PRODUCT_CODE
